### ISSUE TITLE
Different behaviour then your gifs 

### ISSUE THREAD

**Issue by lalamm** [guimcaballero/bevy_rhythm#1]
I saw your tutorial on bevy discord and decided to cehck it out!

After I added target arrows  I get this weird behaviour.

- First arrow skips 1/3 of the screen
- Target arrows become available after all arrows have ended

First I thought i made something wrong but when i looked at the commit 9a7e904 and ran it on my computer I got the same behaviour. Made following gif
![weird](https://user-images.githubusercontent.com/13511791/107431007-2cd4b980-6b26-11eb-961c-3e444307071d.gif)

Running on
Distributor ID: Ubuntu
Description:    Ubuntu 20.10
Release:        20.10
Codename:       groovy

**Comment by guimcaballero** [comment]
Hello! It appears that Bevy is taking longer to load the sprites. Could you try running the game in release mode with `cargo run --release` and seeing if the problem persists?

**Comment by lalamm** [comment]
That was it! Thank you, will do the rest of the tutorial in release then I guess :)

**Comment by guimcaballero** [comment]
Good to know! I'll add a note on the tutorial for other people.
